### ISSUE TITLE
Define UX inconsistencies in current Joomla version

### ISSUE THREAD

**Issue by crystalenka** [joomla/jxt#5]

**Comment by HLeithner** [comment]
Better trash handling would be great for example an icon "show trash" or something next to the "options" button

**Comment by coolcat-creations** [comment]
Should we collect the issues inside this post or somewhere else?

**Comment by crystalenka** [comment]
Somewhere else for sure but I wanted to get it out of the chat where it would disappear forever 😝

I will figure out where exactly over the weekend or next week, right now I'm not at the computer

**Comment by crystalenka** [comment]
Closing this issue as we've pulled out several impactful items we can address from @pe7er's observations. Please see referenced issues. (I'm going through your spreadsheet next too, Elisa!)

Thank you!
